creating an array using numpy

In [23]:
import numpy as np
import pandas as pd

In [27]:
arr = np.array([1,2,5,4,6,8,3,2,1,4,5,7,8,562,1,2,4,5])
print(arr.reshape(3,-1).shape)

(3, 6)


In [26]:
df = pd.DataFrame([[15,12],
                   [33,54],
                   [10,32]],
                  index = ['one','two','three'],
                  columns = ['col1','col2'])

print(df.filter(regex = 'e$', axis = 0).shape)
print(df.filter(regex = '^c', axis = 1).shape)

(2, 2)
(3, 2)


In [4]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.size

4

In [7]:
arr.ndim

1

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr1 = np.array([100,78,65,45],dtype = 'int8')

In [10]:
arr1 = np.array([1,2,3,4],dtype = "int8")

In [11]:
arr1.dtype

dtype('int8')

creating matrix in numpy

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [13]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [14]:
arr2.size

6

In [15]:
arr2.ndim

2

In [16]:
arr2.shape

(2, 3)

In [17]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [18]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
arr3.size

12

In [20]:
arr3.ndim

3

In [21]:
arr3.shape

(2, 2, 3)

In [22]:
a = np.array(42) # 0-d, single int
a1 = np.array([42]) # 1-d
b = np.array([1,2,3,4,5]) # 1-d
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [23]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [24]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


access element in arrays and matrics , similar to slicing

In [25]:
arr = np.array([1,2,3,4])
print(arr[0:2])

[1 2]


In [26]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr2[0,1]) #2
print('5th element on 2nd row: ',arr2[1,4] ) # 10
print(arr2[1,0:3])# 2 row, first 3 elem

2nd element on 1st row:  2
5th element on 2nd row:  10
[6 7 8]


In [27]:
arr3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2*2*3
print(arr3[0,1,2])

6


Slicing works in numpy array as well

In [28]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [29]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2]) # start: stop: step

[2 4]


In [30]:
print(arr[::2])

[1 3 5 7]


slicing of 2-d, 3-d arrays

In [31]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2*5

In [32]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [33]:
arr[0:2,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [34]:
print(arr[1, 1:4])

[7 8 9]


In [35]:
print(arr[0:2,2])

[3 8]


In [41]:
arr1 = np.random.randint(1, 101, 100).reshape(5, -1)
print(arr1)

[[ 48  68   6  58  95  54  64 100  40  61  22  94  31  78  31  27  99  48
   18  16]
 [  3  75  40  62  75  16   2  86  16  26   3  34  67  74  53  14  99  91
   21   9]
 [ 31  44  19  31  54  48  91  23   3   1  12  12  66  38  61  85  18  66
    7  25]
 [ 92  70  46  74  21  30  23  34  97   9  85  33  74   3  10  55  34  36
   96 100]
 [ 18   9  51  56  57  66  76  12  39  36  39  68  78  98  52   3   6  22
   66  23]]


In [1]:
import numpy as np



A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]



print(B)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
