NumPy Array Copy vs View

The main difference between a copy and a view of an array is that
the copy is a new array, and the view is just a view of the original array.


In [1]:
import numpy as np

# The copy SHOULD NOT be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
copied_arr = arr.copy()
arr[0] = 42

print(arr)
print(copied_arr)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

[[  1   2   3]
 [100   5   6]
 [  7   8   9]]


In [5]:
arr2 = np.array([1, 2, 3, 4, 5])
viewed_array = arr2.view()
arr2[0] = 42

print(arr2)
print(viewed_array)

[42  2  3  4  5]
[42  2  3  4  5]


Shape and Dimension

In [6]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # 2 * 4

print(arr.ndim)
print(arr.shape)

2
(2, 4)


In [7]:
np.array([1,2], ndmin = 2).ndim

2

In [8]:
arr2 = np.array([1,2], ndmin = 4)
print(arr2.ndim)
print(arr2.shape)
print(arr2)

4
(1, 1, 1, 2)
[[[[1 2]]]]


In [9]:
arr3 = np.array([[[[1,2]]]])
print(arr3.ndim)
print(arr3.shape)
print(arr3)

4
(1, 1, 1, 2)
[[[[1 2]]]]


Reshaping


In [10]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr3 = arr2.reshape(2,6)
print(arr3)
print(arr3.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2


In [46]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # 1- d Array

newarr = arr2.reshape(4, 3) # 4 * 3
print(newarr.ndim)
print(newarr)

2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
arr4 = arr2.reshape(2,2,3) # 2*2*3
print(arr4)
print(arr4.ndim)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [13]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr3 = arr3.reshape(2, 3, 2) # 2 * 3 * 2

print(newarr3.ndim)

newarr3[0][0][0] = 100
print(arr3[0])

print(arr3)

3
100
[100   2   3   4   5   6   7   8   9  10  11  12]


Iteration in ndarray - numpy


In [14]:
arr = np.array([1, 2, 3]) # 1-d array
for value in arr:
  print(value)

1
2
3


In [15]:
arr = np.array([1, 2, 3]) # 1-d array

for x in arr:
  print(type(x))
  print(x)

<class 'numpy.int64'>
1
<class 'numpy.int64'>
2
<class 'numpy.int64'>
3


In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) # 2-d array

for x in arr:
  print(type(x))
  print(x)

<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>
[4 5 6]


In [17]:
for row in arr:
  for elem in row:
    print(elem)
    print(type(elem))

1
<class 'numpy.int64'>
2
<class 'numpy.int64'>
3
<class 'numpy.int64'>
4
<class 'numpy.int64'>
5
<class 'numpy.int64'>
6
<class 'numpy.int64'>


In [18]:
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # 3-d array
for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [20]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])  # 3-d array

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [21]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3-d
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [22]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for idx, value in np.ndenumerate(arr):
  print(idx,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [23]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3-d

print("Printing using nditer")
for x in np.nditer(arr):
  print(x)

Printing using nditer
1
2
3
4
5
6
7
8


In [24]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


Joining Arrays - Concatenating Arrays

In [25]:
arr1 = np.array([1, 2, 3]) # 1- d

arr2 = np.array([4, 5, 6])

arr3 = np.concatenate([arr1,arr2])
print(arr3)

[1 2 3 4 5 6]


In [26]:
arr1 = np.array([1, 2, 3]) # 1- d

arr2 = np.array([4, 5, 6])

arr3 = np.concatenate([arr1, arr2])

print(arr3)

[1 2 3 4 5 6]


In [27]:
arr1 = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]]) # 3-d array

arr2 = np.array([[[11, 22], [33, 44]],[[55, 66], [77, 88]]])

print(arr1)
print(arr2)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]


In [28]:
arr4 = np.concatenate([arr1,arr2], axis = 0)
print(arr4)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]


In [29]:
new_arr = np.concatenate([arr1, arr2]) # 4 * 2
print(" Joining along rows")
print(new_arr)

# same as
new_arr = np.concatenate([arr1, arr2], axis = 0) # 4 * 2
print("Joining along rows")
print(new_arr)

 Joining along rows
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
Joining along rows
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]


In [30]:
arr3 = np.concatenate([arr1, arr2], axis=1) # 2 * 4 - columns

print("Joining along columns")
print(arr3)

Joining along columns
[[[ 1  2]
  [ 3  4]
  [11 22]
  [33 44]]

 [[ 5  6]
  [ 7  8]
  [55 66]
  [77 88]]]


Filtering

In [31]:
arr = np.array([41, 42, 43, 44])
filter = [False,True,False,True]
print(arr[filter])


[42 44]


In [32]:
arr = np.array([41, 42, 43, 44])

even_filter = [False, True, False, True] # bool

newarr = arr[even_filter] # 42, 44

print(newarr)

[42 44]


In [33]:
arr = np.array([41, 42, 43, 44])
# Create an empty list
filter = []
for x in arr:
  if x%2 == 0:
    filter.append(True)
  else:
    filter.append(False)

print(arr[filter])

[42 44]


In [34]:
filter = (arr % 2 == 0)
print(arr[filter])

[42 44]


In [35]:
# Creating the Filter Array

arr = np.array([41, 42, 43, 44])

# Create an empty list
even_filter = [] # bool

# go through each element in arr
for element in arr:
  # if the element is even, set the value to True, otherwise False:
  if element % 2 == 0:
    even_filter.append(True)
  else:
    even_filter.append(False)

newarr = arr[even_filter]

print(newarr)

[42 44]


In [36]:
# Creating Filter Directly From Array

arr = np.array([41, 42, 43, 44])

filter_arr = (arr % 2 == 0)

print(filter_arr)

print(type(filter_arr))

newarr = arr[filter_arr]

print(newarr)

[False  True False  True]
<class 'numpy.ndarray'>
[42 44]


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
filter = (arr % 2 == 0)
print(filter)
print(arr[filter])

[[False  True False]
 [ True False  True]]
[2 4 6]


In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

arr2 = arr.reshape(2,3)

filter_arr = arr2 % 2 == 0

print(filter_arr)

arr3 = arr2[filter_arr]
print(arr3)
print(arr3.ndim)


[[False  True False]
 [ True False  True]]
[2 4 6]
1


In [39]:
arr = np.array([1,2,3])
arr_copy = arr.copy()
arr1 = arr
arr_view = arr.view()
print(arr)
print(arr_copy)
print(arr1)
print(arr_view)

[1 2 3]
[1 2 3]
[1 2 3]
[1 2 3]


In [40]:
print(id(arr))
print(id(arr_copy))
print(id(arr1))
print(id(arr_view))

4666001520
4666002672
4666001520
4666002192


In [41]:
arr[0] = 43

In [42]:
print(arr)
print(arr_copy)
print(arr_view)

[43  2  3]
[1 2 3]
[43  2  3]


In [43]:
print(id(arr))
print(id(arr_copy))
print(id(arr_view))

4666001520
4666002672
4666002192


In [44]:
print(id(arr_view.base))
print(id(arr))

4666001520
4666001520
